### ISSUE TITLE
Using a custom logger requires set_logger in every task

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/log#21]
<a href="https://github.com/seanmonstar"><img src="https://avatars.githubusercontent.com/u/51479?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [seanmonstar](https://github.com/seanmonstar)**
_Wednesday Aug 27, 2014 at 16:24 GMT_

_For earlier discussion, see https://github.com/rust-lang/rust/issues/16794_

_This issue was labelled with: A-libs in the Rust repository_

----

Currently, the logger is stored in TLS. It's fine to setup a logger at the start of your program, but if you use `spawn` a lot, it's cumbersome to remember in each call to setup your logger again.

I think tasks should inherit the logger from the task that spawned it, perhaps with an option to turn it off (less important).

cc #3309

**Comment by seanmonstar** [comment]
This issue is no longer relevant, since log is now a global logger, and not stored per thread.

**Comment by steveklabnik** [comment]
Thanks!
