### ISSUE TITLE
Implement Error trait for SetLoggerError

### ISSUE THREAD

**Issue by galsondor** [rust-lang/log#22]
The return value from function `set_logger()` is `Result<(), SetLoggerError>`, which follows the [improved error handling](http://lucumr.pocoo.org/2014/11/6/error-handling-in-rust/) pattern.  However, `SetLoggerError` does not implement the `Error` trait, which prevents use of the `try!` macro.  Recommend implementing the `Error` trait.

**Comment by galsondor** [comment]
Implementing the `Error` trait was simple and straight forward, requiring the addition of `use std::error` and 3 lines to implement `Error::description()`.  Implementing `Error::cause()` is not necessary.  One unit test ensures it works.  Pull request #23 contains the changes.

**Comment by sfackler** [comment]
I think this can be closed now?

**Comment by alexcrichton** [comment]
Indeed!
