### ISSUE TITLE
nothing prints out

### ISSUE THREAD

**Issue by jinfagang** [rust-lang/log#326]
there is nothing prints out:

        warn!("but this is not implemented yet!")

i got nothing on terminal

**Comment by sfackler** [comment]
> In order to produce log output executables have to use a logger implementation compatible with the facade. There are many available implementations to choose from, here are some of the most popular ones:

https://docs.rs/log/0.4.6/log/#available-logging-implementations

**Comment by clearloop** [comment]
try this:

```rust
#[macro_use]
extern crate log;

fn main() {
  // set `ENV`
  ::std::env::set_var("RUST_LOG", "warn");

  warn!("well, this has already implemented");
}
```

**Comment by KodrAus** [comment]
We do also have some [examples in `env_logger`](https://github.com/sebasmagri/env_logger/blob/master/examples/default.rs) that show you how to get started and specify default values for environment variables that aren’t present.
