### ISSUE TITLE
Move Repository To rust-lang

### ISSUE THREAD

**Issue by XAMPPRocky** [rust-lang/log#360]
Hello, the current `rust-lang-nursery` organisation is considered deprecated, and the Rust Programming Language organisation is trying to consolidate managing Rust's GitHub organisations, as such we'd like you to consider moving your repository to the main `rust-lang` organisation instead. 

### How Do I Move To `rust-lang`?
You won't be able to transfer your repository directly, you'll need to transfer your repository to @Mark-Simulacrum, who will then move your repository to the `rust-lang` organisation.

### Deprecating
If you no longer intend to maintain this repository, please let us know and we will take of deprecating the project.

**Comment by sfackler** [comment]
We should transfer it to rust-lang.

**Comment by Mark-Simulacrum** [comment]
Note that gh-pages branch will not transfer perfectly, i.e., links will break -- you can manually set up redirects; I'm not sure if we're using the gh-pages branch here anymore. Once you're fine with that I can take care of the transfer for you.

**Comment by sfackler** [comment]
Our docs are on docs.rs, so the gh-pages shouldn't be a problem.

**Comment by Mark-Simulacrum** [comment]
Okay - I can actually transfer the repo directly I think (no need for the intermediate step) -- just give me an explicit ping here when you're ready to go ahead.

**Comment by sfackler** [comment]
Let's do it!

**Comment by Mark-Simulacrum** [comment]
Done!
