### ISSUE TITLE
Support for tool for verification and construction of valid RUST_LOG directives

### ISSUE THREAD

**Issue by yaahc** [rust-lang/log#363]
I'm thinking about writing a tool to help verify or generate `RUST_LOG` directives. Something that, given a binary and a `RUST_LOG` string can check that each module path in the string is valid, or when given just a binary can output all the module paths that are valid or maybe give you a TUI that lets you filter and select these paths and set levels and then outputs the appropriate `RUST_LOG` string you need to source.

I don't really know how to do this, I'm hoping that there's some sort of binary inspection that could be done to see all the calls to the various `info!` like macros and extract the module setting that they're set to. I figured I'd open an issue to get the conversation started and possibly get guidance on how best to go about implementing such a tool.

**Comment by sfackler** [comment]
`RUST_LOG` is specific to env_logger - you may want to file this over there: https://github.com/sebasmagri/env_logger/.

**Comment by yaahc** [comment]
Oh of course, thank you
