### ISSUE TITLE
Potential behaviour regression with named formatting arguments

### ISSUE THREAD

**Issue by kubkon** [rust-lang/log#372]
Current release version `0.4.10` seems to have introduced a regression in behaviour in the sense that named formatting arguments, which were legal in the previous versions, are now illegal.

Minimal example:

```rust
fn main() {
    let name = "John";
    log::info!("Hello, {name}", name = name);
}
```

Is this intended behaviour or a bug?

**Comment by kubkon** [comment]
NB, works with the previous release `0.4.8`.

**Comment by bbqsrc** [comment]
This is quite broken. 0.4.8 works, newer version broken. Format args do not work and cause build errors.

**Comment by estk** [comment]
@KodrAus or @sfackler  Maybe .10 should be yanked? I have the same issue.

**Comment by maplant** [comment]
@estk agree that 0.4.10 should be yanked.

**Comment by sfackler** [comment]
Yanked.

**Comment by KodrAus** [comment]
Ok. It looks like we just haven’t built up the CI coverage yet to be able to make changes to the `log` macros without breaking things. I’ll add some more cases, revert our implementation back to what it was (but retain #366) and we can explore macro changes externally.

**Comment by KodrAus** [comment]
`master` has been updated to use the old macro implementation and we've got a failing test on the `kv_macro` branch the new one lives on to track this. Any new releases we push out now will be using the same macros as `0.4.8`.

I'll go ahead and close this one now. Thanks for the report!
