### ISSUE TITLE
How to make log  print to console

### ISSUE THREAD

**Issue by Ace-Tang** [rust-lang/log#376]
I want to log to console for easy debug, but can not find a way to do

```
use log::info;

fn main() {
    println!("use println Hello, world!");
    info!("use into Hello, world!");
```

$ ./target/debug/log 
use println Hello, world!

I can only get println! output, can I get info! output to console ?

**Comment by sfackler** [comment]
https://docs.rs/log/0.4.10/log/#available-logging-implementations

**Comment by Ace-Tang** [comment]
Hi @sfackler , does that means log not support log to console, I should choose other implement ?

**Comment by sfackler** [comment]
It means you should pick a logging implementation that prints to the console (like env_logger for example)

**Comment by Ace-Tang** [comment]
Already got this ! thanks for your quick answer.
this is a good example https://docs.rs/env_logger/0.7.1/env_logger/
