### ISSUE TITLE
Failed to run custom build command - Permission denied on termux

### ISSUE THREAD

**Issue by whizsid** [rust-lang/log#383]
I can not compile my rust project on my android phone. I am using the [termux](https://termux.com/) terminal app to build. This is the error that I am getting :-

```
error: failed to run custom build command for 'log v0.4.8'

Caused by:
  could not execute process `.../build-script-build` (never executed)

Caused by:
 Permission denied (os error 13)
warning: build failed, waiting for other job to finish...
error: build failed
```

This is my repo:- https://github.com/whizsid/json-api-tester

**Comment by KodrAus** [comment]
The build script here is very simplistic. This looks more like an issue in the android environment.

It’s been a while here so I’ll go ahead and close this one as I don’t think there’s much for us to chase up in `log`, but I’d be keen to hear how it goes attempting to build now.
