### ISSUE TITLE
Error! logging on Windows x64 Rust prints nothing without env variable

### ISSUE THREAD

**Issue by Velocity-** [rust-lang/log#39]
The example tells me:

`Log levels are controlled on a per-module basis, and by default all logging is disabled except for error!`

However, when I copy the example...

```
#[macro_use]
extern crate log;
extern crate env_logger;

fn main() {
	env_logger::init().unwrap();
	error!("this is printed by default\n");
}
```

.. and `cargo build` it (successfully) and then `cargo run` it, the console prints nothing. However, once I type this in the cmd window:

`@set RUST_LOG=ERROR`

everything works fine. I'm not sure if this is intended to be this way, but if I read the example description I'd assume this is a bug.

Environment:
Windows 8.1 64-bit
Rustc 1.0.0-beta.4 (850151a75 2015-04-30) (built 2015-05-01)
Cargo 0.2.0-nightly (efb482d 2015-04-30) (built 2015-04-30)

Cargo dependencies:
`[dependencies]
log = "0.3.1"
env_logger = "0.3.0"`

**Comment by sfackler** [comment]
I think that's just a typo in the docs - all logging is disabled by default.

**Comment by sfackler** [comment]
As a followup, it turns out that the documented behavior was what was actually intended. `env_logger` now outputs error-level log events by default: https://github.com/rust-lang/log/commit/f2aad6bb23636dca801d366eca227ddcafd268a7

**Comment by Velocity-** [comment]
Awesome, thanks for taking care of this! Glad I could help improve log :)
