### ISSUE TITLE
Target filter

### ISSUE THREAD

**Issue by vagola** [rust-lang/log#403]
I would like to have ability to include/exclude certain targets to improve debug experience.

**Comment by Thomasdezeeuw** [comment]
@vagola this can be implement by the `Log` implementation, you can use the [`Record::target`](https://docs.rs/log/0.4.8/log/struct.Record.html#method.target) method to get the target. For example using [`env_logger`](https://docs.rs/env_logger) you can use `RUST_LOG=main=info` environment variable to only log messages from the `main` module.
