### ISSUE TITLE
Log custom 'line', 'file' and 'module'

### ISSUE THREAD

**Issue by inzanez** [rust-lang/log#411]
Is there a way to overwrite the `line`, `file` and `module` parameters of a log message?

I thought of  building a simple crate to facilitate logging, using `map_err`; something like this:

```
   ...
   ...
    fn log_error<D>(self, message: D) -> Result<T, E>
    where
        D: Display + Send + Sync,
        Self: Sized,
    {
        self.map_err(|err| {
            let caller = std::panic::Location::caller();
            error!("{}: {}", message, err.to_string());
            err
        })
    }
    ...
```

This all works quite well so far, but as the actual call to `error!` happens inside my helper-crate now, the parameters `line`, `file` and `module` will not reflect the actual location. So I thought I may use `std::panic::Location::caller` to get the actual location, which works fine except for the `module` part. But there seems to be no way to actually pass that information along with log messages.

**Comment by sfackler** [comment]
Rather than using the macros, you can get ahold of the logger directly: https://docs.rs/log/0.4.11/log/fn.logger.html, assemble a `Record` yourself and then call log: https://docs.rs/log/0.4.11/log/trait.Log.html#tymethod.log.

**Comment by inzanez** [comment]
> Rather than using the macros, you can get ahold of the logger directly: https://docs.rs/log/0.4.11/log/fn.logger.html, assemble a `Record` yourself and then call log: https://docs.rs/log/0.4.11/log/trait.Log.html#tymethod.log.

Hm, ok, I wasn't aware of this. Well, I'll give that a try then! Many thanks! :-)
