### ISSUE TITLE
How the log works with Cargo.toml at compiling level?

### ISSUE THREAD

**Issue by uynap** [rust-lang/log#412]
Based on the documents, I have the Cargo.toml like:
```
[dependencies]
log = { version = "0.4", features = ["max_level_debug", "release_max_level_warn"] }
```

And the code:
```rust
use log::*;

fn main() {
    println!("Hello, world!");
    info!("this is info");
    debug!("this is debug");
    warn!("this is warn");
    trace!("this is trace");
}

```

When I `cargo run`, I can only see the `println!`. Did I miss something or made any mistake?

**Comment by KodrAus** [comment]
Hi @uynap :wave:

The `log` crate doesn't actually write anything itself. You can use a library like [`env_logger`](https://github.com/env-logger-rs/env_logger) to write log messages to the terminal.

If you'd like to test how the max level flags work, you can also use a command like [`cargo expand`](https://github.com/dtolnay/cargo-expand) to see what each of those statements expand to at compile time.

**Comment by uynap** [comment]
Thank you @KodrAus . It's working now. 👍

**Comment by uynap** [comment]
> Hi @uynap 👋
> 
> The `log` crate doesn't actually write anything itself. You can use a library like [`env_logger`](https://github.com/env-logger-rs/env_logger) to write log messages to the terminal.
> 
> If you'd like to test how the max level flags work, you can also use a command like [`cargo expand`](https://github.com/dtolnay/cargo-expand) to see what each of those statements expand to at compile time.

btw. `cargo expand` is a really useful tool.
