### ISSUE TITLE
Idempotent logging initialization

### ISSUE THREAD

**Issue by piegamesde** [rust-lang/log#415]
Currently, the logger may not be set more than once and will return an error on all succeeding attempts. However, I think that the try to set *the same* logger twice should return `Ok` in order to make the function idempotent.

Motivation: See the documentation of `env_logger` [for example](https://docs.rs/env_logger/0.7.1/env_logger/#capturing-logs-in-tests):

```rust
#[cfg(test)]
mod tests {
    fn init() {
        let _ = env_logger::builder().is_test(true).try_init();
    }

    #[test]
    fn it_works() {
        init();

        info!("This record will be captured by `cargo test`");

        assert_eq!(2, 1 + 1);
    }
}
```

The logger needs to be initialized for each test because there is no "run before all tests" method in Rust. With the proposed changed, the `init` method could simply call `unwrap` (or `env_logger::init()`) instead of explicitly swallowing a potential error.

**Comment by KodrAus** [comment]
We could actually “fix” this over in `env_logger` by offering a more convenient `env_logger::init_test()` method that you can just call inline.

Longer term I wonder whether there’s some kind of magic we could pull to register a global logger using an API inspired by global allocators:

```rust
#[global_logger]
static LOGGER: GlobalLog = env_logger::GlobalTestLogger;
```

**Comment by piegamesde** [comment]
I'd prefer solving this in the `log` crate itself to avoid implementing the solution for every single logging implementation. I was just using `env_logger` as an example because I stumbled over it.

What you suggest is probably doable using the [ctor](https://docs.rs/ctor/0.1.16/ctor/) crate. [inventory](https://docs.rs/inventory/0.1.9/inventory/) and [label](https://docs.rs/label/0.6.0/label/) are higher level wrappers that use it.

**Comment by sfackler** [comment]
How would the log crate determine if "the same" logger is being installed without modifying every single logging implementation?

**Comment by piegamesde** [comment]
@sfackler Fair point. This would probably extending `Log` with `Eq` and `Any`, but I somewhat hope that a fallback solution based on pointer equality is feasible.

**Comment by sfackler** [comment]
The pointers would not be equal in the env-logger-in-test workflow. env-logger allocates a new logger each time init is called.

**Comment by jrose-signal** [comment]
> Longer term I wonder whether there’s some kind of magic we could pull to register a global logger using an API inspired by global allocators:
> 
> ```rust
> #[global_logger]
> static LOGGER: GlobalLog = env_logger::GlobalTestLogger;
> ```

> What you suggest is probably doable using the [ctor](https://docs.rs/ctor/0.1.16/ctor/) crate. [inventory](https://docs.rs/inventory/0.1.9/inventory/) and [label](https://docs.rs/label/0.6.0/label/) are higher level wrappers that use it.

Static initializers aren't great because they impact launch time (and run in an unspecified order). An alternative might be the "declare a symbol defined elsewhere approach" described in "[The Embedonomicon](https://rust-embedded.github.io/embedonomicon/singleton.html)".

I ran into this today and went with a static constructor (and crossed fingers for getting invoked exactly once), but I'd be happy to prototype the "declare a symbol" approach if there's interest. It still wouldn't be universally applicable though because of dynamic libraries, which don't allow you to just leave a symbol unresolved at link time on Windows. (On macOS that's also disallowed by default, but you can pass linker flags to get around it.)

**Comment by DesmondWillowbrook** [comment]
> 
> 
> Currently, the logger may not be set more than once and will return an error on all succeeding attempts. However, I think that the try to set _the same_ logger twice should return `Ok` in order to make the function idempotent.
> 
> Motivation: See the documentation of `env_logger` [for example](https://docs.rs/env_logger/0.7.1/env_logger/#capturing-logs-in-tests):
> 
> ```rust
> #[cfg(test)]
> mod tests {
>     fn init() {
>         let _ = env_logger::builder().is_test(true).try_init();
>     }
> 
>     #[test]
>     fn it_works() {
>         init();
> 
>         info!("This record will be captured by `cargo test`");
> 
>         assert_eq!(2, 1 + 1);
>     }
> }
> ```
> 
> The logger needs to be initialized for each test because there is no "run before all tests" method in Rust. With the proposed changed, the `init` method could simply call `unwrap` (or `env_logger::init()`) instead of explicitly swallowing a potential error.

Slightly unrelated to the _proposed_ solution, but a work-around I came up with when building the [`log_err`](https://crates.io/crates/log_err) was having a `mut static` and setting that when a logger was initialized.

```rust
static mut LOGGER_SET_UP: bool = false;
#[test]
fn test_log_unwrap () {
  unsafe {if !LOGGER_SET_UP {setup_logger(); LOGGER_SET_UP = true;}}
}

```

**Comment by Thomasdezeeuw** [comment]
> Slightly unrelated to the _proposed_ solution, but a work-around I came up with when building the [`log_err`](https://crates.io/crates/log_err) was having a `mut static` and setting that when a logger was initialized.
> 
> ```rust
> static mut LOGGER_SET_UP: bool = false;
> #[test]
> fn test_log_unwrap () {
>   unsafe {if !LOGGER_SET_UP {setup_logger(); LOGGER_SET_UP = true;}}
> }
> ```

@DesmondWillowbrook reading and writing from `LOGGER_SET_UP` like that is a data race and is undefined behaviour. You should use an `std::sync::atomic::AtomicBool` for that. But since the log crate essentially already does that for you, I usually try to set the logger in each test and ignore the error.

**Comment by KodrAus** [comment]
Just coming back through some triage. It sounds like we don't have any really compelling alternative initialization strategies. I'll go ahead and close this one, but if any alternative strategies emerge that do make a meaningful difference for most users then we can consider those.

Thanks for all the input everyone!
