### ISSUE TITLE
Cannot import LogMetadata

### ISSUE THREAD

**Issue by sybblow** [rust-lang/log#42]
I am trying to write a customized logger, but I got some issue like this:
```
xxxxx.rs:17:30: 17:41 error: unresolved import `log::LogMetadata`. There is no `LogMetadata` in `log`
xxxxx.rs:17 use log::{LogRecord,LogLevel,LogMetadata,LogLocation,set_logger};
```
It's strange that __only__ `LogMetadata` not imported properly.

BTW, I specified `log` version to exactly __0.3.1__ in `Cargo.toml`.

```toml
[dev-dependencies]
log = "0.3.1"
```

**Comment by alexcrichton** [comment]
Are you sure that `0.3.1` of this crate is being used? The specification "0.3.1" means "semver compatible with 0.3.1" which includes 0.3.0 which may not have had this export.

**Comment by sybblow** [comment]
I made a mistake. I should use `dependencies` rather than `dev-dependencies`. But the  error message is confused, maybe I should submit a issue to **cargo**.
