### ISSUE TITLE
error: failed to run custom build command for `log v0.4.11` on M1 Mac rustc 1.49.0-beta.4 

### ISSUE THREAD

**Issue by Triscuit-circuit** [rust-lang/log#425]
I was doing some compile tests on the M1 macs on rustc 1.49.0-beta.4 compiler with some projects that I have and noticed that cargo kept having an error compiling log. 

Even with an Hello World program that has log as a listed dependency it errors with:
```cargo build

Compiling log v0.4.11
Compiling cfg-if v0.1.10
error: failed to run custom build command for `log v0.4.11`

Caused by:
  process didn't exit successfully: `/Users/user/CLionProjects/untitled/target/debug/build/log-564e465c28a8f328/build-script-build` (signal: 9, SIGKILL: kill)
```
feel free to let me know if more information is needed to fix this issue

**Comment by sfackler** [comment]
https://github.com/rust-lang/rust/issues/79761
