### ISSUE TITLE
static item is never used: `LOC` ?

### ISSUE THREAD

**Issue by buster** [rust-lang/log#43]
Am i the only one getting warnings like this:

```
<log macros>:3:1: 5:8 warning: static item is never used: `LOC`, #[warn(dead_code)] on by default
<log macros>:3 static LOC : $ crate:: LogLocation = $ crate:: LogLocation {
<log macros>:4 __line : line ! (  ) , __file : file ! (  ) , __module_path : module_path ! (
<log macros>:5 ) , } ; let lvl = $ lvl ; if ! cfg ! ( log_level = "off" ) && (
<log macros>:1:1: 13:64 note: in expansion of log!
<log macros>:13:1: 13:62 note: expansion site
<log macros>:1:1: 13:64 note: in expansion of log!
<log macros>:4:1: 4:53 note: expansion site
<log macros>:1:1: 4:57 note: in expansion of debug!
src/parser.rs:8:5: 8:38 note: expansion site

```

I'm not aware that i did something wrong.. i have a library and lib.rs basically contains the import and the #[macro_use] statement.
The expansion sites are debug!() statements..

**Comment by buster** [comment]
Also googling i can find mostly travis-ci logs, so it looks like others have this warning as well:

https://www.google.de/search?output=search&sclient=psy-ab&q=static%20item%20is%20never%20used%3A%20%60LOC%60&oq=&gs_l=&pbx=1#q=rust+static+item+is+never+used:+%60LOC%60

**Comment by sfackler** [comment]
Is the debug statement in dead code? The dead code lint is recursive, so it'll warn about both an unused function and the statics defined inside of it. I'll update the macro regardless to have it bypass the dead code warning.

**Comment by buster** [comment]
Yes, i refactored a lot and still have quite a lot of dead or (yet) unused code. Nevertheless this warning takes up the majority of output, so it's quite distracting. I'd appreciate the warning being gone, thanks! :)

**Comment by LukasKalbertodt** [comment]
This bug still exists in version 0.3.1, which is the newest version on crates.io. Why hasn't the crates.io package been updated since March, 28?

**Comment by alexcrichton** [comment]
@LukasKalbertodt I just published a new version, thanks for the reminder!

**Comment by LukasKalbertodt** [comment]
@alexcrichton :)
