### ISSUE TITLE
Stabilize kv_unstable

### ISSUE THREAD

**Issue by KodrAus** [rust-lang/log#436]
This is part of #328 

I think we've explored enough of this design space now and the API has been in use within the `tide` project for some time now with their own kv-capable logging macro.

By stabilizing just the backend (non-macro-supported) `kv` module we can let users depend on this with confidence so that projects like `tracing` can also utilize it.

# Migration path

The `kv` API will remain an opt-in optional API. All features that currently begin with `kv_unstable` will be changed to `kv`. We can keep these old unstable features around for a while if we need.

Any other changes that are needed should be included here.

# Steps

- [x] Public API review of the `kv` module
- [x] Stabilize [`sval`](https://github.com/sval-rs/sval)
- [x] Stabilize [`value-bag`](https://github.com/sval-rs/value-bag)
- [ ] Documentation and examples

cc @yoshuawuyts

**Comment by Thomasdezeeuw** [comment]
I don't know what the plan is for the `kv_unstable_std` feature, but can that be removed? Surely most users mean to enable `kv_unstable_std` if `std` and `kv` are enabled.

**Comment by KodrAus** [comment]
@Thomasdezeeuw unfortunately it’s a limitation of Cargo features. Since it’s not possible to activate a feature of a dependency when two unrelated features are active we need one that covers them both.

**Comment by Thomasdezeeuw** [comment]
@KodrAus in the code you can use `#[cfg(all(feature = "kv", feature = "std"))]` in stead of `#[cfg(feature = "kv_unstable_std")]`, removing the `kv_unstable_std` feature.

**Comment by KodrAus** [comment]
@Thomasdezeeuw we can do that in code, but we also have dependencies that need their own `std` features enabled too.

**Comment by Thomasdezeeuw** [comment]
@KodrAus could you make another release to try the new macro syntax?

**Comment by KodrAus** [comment]
@Thomasdezeeuw Will do! I'll get the ball rolling on this now.

**Comment by Thomasdezeeuw** [comment]
@KodrAus any update on a release? We've been using the git version without issues for a while (including the new macro syntax).

**Comment by KodrAus** [comment]
@Thomasdezeeuw I've been waiting for some feedback from the wider project on https://github.com/rust-lang/log/issues/343#issuecomment-1002851191, but it's been a bit quiet. I'm pretty confident in the direction we're going though and that we're not heading down a path we'll regret later so will push ahead.

**Comment by KodrAus** [comment]
I've opened #485 to get a release out the door. I'm just going to run through the diff, but if you had a chance to take a look too @Thomasdezeeuw that would be much appreciated! :bow:
