### ISSUE TITLE
Release 0.4.14

### ISSUE THREAD

**Issue by KodrAus** [rust-lang/log#437]
There was a change to the way the `kv_unstable` API works between `0.4.11` and `0.4.13` that requires users to add the `kv_unstable_std` feature instead of just `std`.

We do reserve the right to break this feature in patch bumps (otherwise we'd never be able to develop it), but don't want to drop broken code without supporting the people who've taken bets on it.

This issue will track coordinating that release.

# Libraries to update

Direct dependencies on `log` with `kv_unstable`:

- [ ] https://github.com/facebookincubator/reindeer
- [ ] https://github.com/facebookexperimental/eden
- [ ] https://github.com/facebook/relay
- [ ] https://github.com/facebook/hhvm
- [ ] https://github.com/wafflespeanut/paperclip
- [ ] https://github.com/rmanoka/async-scoped
- [ ] https://github.com/async-rs/async-std
- [ ] https://github.com/wusyong/tokio-async-std
- [x] https://github.com/yoshuawuyts/kv-log-macro (https://github.com/yoshuawuyts/kv-log-macro/pull/8)
- [ ] https://github.com/Gonzih/crabler
- [ ] https://github.com/Gonzih/apod-nasa-scraper-rs
- [ ] https://github.com/kamek-pf/stackdriver-logger
- [ ] https://github.com/michaelmelanson/pinhole
- [ ] https://github.com/sunli829/xlog

Direct dependencies with `kv_unstable` and `std`:

- [ ] https://github.com/sebastiencs/rustorrent (https://github.com/sebastiencs/rustorrent/pull/2)
- [ ] https://github.com/async-rs/async-log/ (https://github.com/async-rs/async-log/pull/14)
- [x] https://github.com/Thomasdezeeuw/std-logger (https://github.com/Thomasdezeeuw/std-logger/pull/30)
- [x] https://github.com/mild-times/localghost (https://github.com/mild-times/localghost/pull/8)
- [ ] https://github.com/lrlna/femme (https://github.com/lrlna/femme/pull/28)
- [x] https://github.com/casualjim/rs-etrade (https://github.com/casualjim/rs-etrade/pull/3)

Known to depend on `log` with `kv_unstable` transitively with `std` implicitly:

- [ ] https://github.com/http-rs/tide (https://github.com/http-rs/tide/pull/776)

**Comment by KodrAus** [comment]
Ok, I've released `0.4.13` as a patch against `0.4.11` (which was the current release on `crates.io`) with just an additional `kv_unstable_std` feature to minimize any disruption from upgrading libraries.

**Comment by anthraxx** [comment]
Just a small question as `0.4.12` has been yanked: will `0.4.14` be based on master and contain the toml changes that have `cfg-if = "1.0"` or will it be based on `0.4.13` which has that reverted?
I'm currently blocked upgrading some of my project dependencies because  `cfg-if = "1.0"` can't be fulfilled, so I'm really looking forward for such a release. :cat:

**Comment by Kixunil** [comment]
@anthraxx what's blocking you? You should be able to use `cfg-if = "0.1"`, even have both dependencies. (May be undesirable but AFAIK `cfg-if` is just a macro, so shouldn't be a big deal.)

**Comment by anthraxx** [comment]
Ok, well, "soft blocking" my CI as clippy is not happy like a hippo :smirk_cat: 
```rust
cargo clippy
    Checking somerustproject v0.0.1 (somerustproject)
error: multiple versions for dependency `cfg-if`: 0.1.10, 1.0.0
  |
note: the lint level is defined here
 --> src/main.rs:1:26
  |
1 | #![deny(clippy::nursery, clippy::cargo)]
```

**Comment by KodrAus** [comment]
@anthraxx It will be based on `master` so will be everything we wish `0.4.12` was.

`0.4.13` is a real stop-gap release so we can help some of the libraries in the OP get prepared for a change in unstable feature flags.

**Comment by Kixunil** [comment]
@anthraxx perhaps change that lint to warning? Seems overly-restrictive to me, especially in this case. Looks like clippy can't be configured more granularly here. I filed https://github.com/rust-lang/rust-clippy/issues/6596

**Comment by KodrAus** [comment]
It's been a little while so I'm going to work on getting this released today.

**Comment by KodrAus** [comment]
Ok, `0.4.14` is now published. There is some breakage in the unstable `kv` API, so I'll keep this issue open for now. Rather than yanking the release this time I'll work on helping any crates that are broken to update.

I'm hoping that we'll only have one more possible release that might make breaking changes to `kv`: the one that stabilizes it.

**Comment by KodrAus** [comment]
;?
'
 o    m nl,l,l,l,l,l,l,l,l,l,l,l,l,l,l,l,uyuuuuuuyuyuyuyuyuyuyuyuyuyuyuyuyuyuyuyuyuyuyuyuyuyuyuyuyuyuyuyuyuyuyuyuyuyuyuyuyuyuyuyuyuyuyuyuyuyuyuyuyuyuyuyuyuyuyuyuyuyuyuyuyuyuyuyuyuyuyuyuyuyuyuyuyuyuyuyuyuyuyuyuyuyuyuyuyuyuyuuyguyyyyyyygnugyg,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,mmm

**Comment by KodrAus** [comment]
This has been out for about a little while now so I'll go ahead and close this one.
