### ISSUE TITLE
`cfg-if` version

### ISSUE THREAD

**Issue by c410-f3r** [rust-lang/log#443]
Maybe I am getting crazy or doing something wrong. One of my projects shows that `log 0.4.13` is requiring `cfg-if 0.1` when issuing `cargo tree -d` but the `Cargo.toml` file of this project needs `cfg-if 1.0` since https://github.com/rust-lang/log/pull/417.

Also, if you go to https://crates.io/api/v1/crates/log/0.4.13/download and see the contents of `Cargo.toml`, this is what will appear:

```
[dependencies.cfg-if]
version = "0.1.2"
```

**Comment by Thomasdezeeuw** [comment]
@c410-f3r see https://github.com/rust-lang/log/blob/master/CHANGELOG.md#0413---2021-01-11.

**Comment by c410-f3r** [comment]
-> ```This is the same as 0.4.11```

@Thomasdezeeuw  I see now. Thanks for your help!
