### ISSUE TITLE
Hash Logs before compilation

### ISSUE THREAD

**Issue by Tamircohen28** [rust-lang/log#444]
I saw there's a develop of kv structure logging. 
First of all, I would like to receive more information about this feature, does it allow keys to be replaced with values on run time? 
Secondley, i'm coming from the information security field and there's a need for the logs to be hashed before compilation.
For example, in the code the developer will write somthing like:
`Info!("invalid password");`
Before compilation it will be hashed so the log messgae won't be included in the binary:
`info!("5e6e951d0b58b694667e07bba01592670f76e6b6");`
After this process we will want to output some map (perhapes json file) of the logs and their `hashed` result so we could know when we receive some hash what it means but an attacker couldn't.
I appolagy if this is not the spot to ask questions or upload this request, i'm new to the open source world.

**Comment by KodrAus** [comment]
Hi @Tamircohen28 :wave:

Sorry for letting this one sit for so long. The structured logging feature effectively lets you associate something roughly like a `HashMap<String, &dyn Display>` with your log records. The data you include in that map is determined at runtime.

It sounds like your needs are fairly specific, and you need a lot of control over what the code in your environment does. That's possibly not a great use-case for the `log` crate, which uses the `format_args` macro under the hood. `format_args` can also produce different strings at runtime, which could thwart your hashing scheme.

**Comment by KodrAus** [comment]
There's not much for us to follow up here in `log` so I'll go ahead and close this one now. If anybody else comes along with similar constraints it would be interesting to hear about them!
