### ISSUE TITLE
`#![feature(format_args_capture)]` support

### ISSUE THREAD

**Issue by hyd-dev** [rust-lang/log#445]
It would be great if this crate supports [`#![feature(format_args_capture)]`](https://github.com/rust-lang/rust/issues/67984). It currently does not ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=9237562522889e215864f9df9ea42c19)):
```rust
#![feature(format_args_capture)]

fn main() {
    env_logger::init();
    let x = 0;
    log::error!("{x}");
}
```
The above program logs `{x}` *without `unused-variables` warning* because `log!` treats single argument specially and uses `__log_format_args!` to validate the argument:
https://github.com/rust-lang/log/blob/1cd39c01fd991e30a7c6eb4ae2b89d9d8af268db/src/macros.rs#L35-L36

I don't understand why `log!` treats single argument specially. The `__private_api_log` code path and `__private_api_log_lit` path should do the same thing (both of them construct `fmt::Arguments`):
https://github.com/rust-lang/log/blob/1cd39c01fd991e30a7c6eb4ae2b89d9d8af268db/src/lib.rs#L1481
https://github.com/rust-lang/log/blob/1cd39c01fd991e30a7c6eb4ae2b89d9d8af268db/src/lib.rs#L1462

If the (redundant?) single argument special treatment is removed, `#![feature(format_args_capture)]` will be supported. That is not a breaking change because `log!` already uses `__log_format_args!` to validate the argument.

I'd like to help if this request is accepted.

**Comment by sfackler** [comment]
That special case existed to minimize the amount of code generated, but it's not compatible with format_args_capture as you pointed out. It should just be removed.
