### ISSUE TITLE
Log without trailing \n (for interactive applications)

### ISSUE THREAD

**Issue by piegamesde** [rust-lang/log#448]
What's a good way to deal with logging in an interactive application? Say I want to input some line of text. If I *log* the input prompt, it will automatically terminate the line, which is ugly. If I *print* it, it will stand out from the other lines (except if I manually replicate the look of my logging implementation), which is ugly as well.

**Comment by sfackler** [comment]
The output is determined by the logger implementation you decide to use (https://docs.rs/log/0.4.14/log/#in-executables). However, logging is generally designed to be used as a diagnostic tool, not for output targeted directly towards a user of your application.

**Comment by piegamesde** [comment]
In CLI applications, printing information to the user is a primary way of communication. And using the existing logging infrastructure is common practice. I could use a logging implementation that never prints newlines, and add '\n' on every statement. However, this will not work well with dependencies that have their own log messages.

Maybe a good solution would be some special log level to signal user interaction? (just an idea)

**Comment by sfackler** [comment]
> Maybe a good solution would be some special log level to signal user interaction? (just an idea)

Again, that is expressly not the goal of this library.
