### ISSUE TITLE
log_err: Related crate to extend log

### ISSUE THREAD

**Issue by DesmondWillowbrook** [rust-lang/log#451]
[`log_err`, a crate](https://github.com/DesmondWillowbrook/rs-log_err) adds `log_expect` and `log_unwrap` to `Result` enums, so the logging implementation can echo the panic message with the `error!` macro.

Maybe this can be added to related works in the README?

**Comment by Thomasdezeeuw** [comment]
@DesmondWillowbrook you can open a pr for this.

**Comment by KodrAus** [comment]
Hey @DesmondWillowbrook :wave:

If you'd like to open a PR to the README to include `log_err` please feel free! To keep our set of open issues focused I'll go ahead and close this one for now, but that's not any indication that we don't want to mention `log_err`.
