### ISSUE TITLE
How to override the default target string?

### ISSUE THREAD

**Issue by keepsimple1** [rust-lang/log#452]
https://github.com/rust-lang/log/blob/9d4206770dd93f07cb27c3e1f41dc21c45031302/src/lib.rs#L22-L24

Is there any example or pointer to how to override the default target string?

Thanks.

**Comment by sfackler** [comment]
https://docs.rs/log/0.4.14/log/macro.warn.html#examples

```
warn!(target: "my custom target", "something bad happened);
```

**Comment by keepsimple1** [comment]
Thank you! In addition to that, is there a way to set a custom target format for all logs? For example: 

by default, the target string is the module path like: `<package_name>::<module_name>:<line_number>` ,  is it possible to change it to `<module_name>:<line_number>` ?  (This is a workspace based project that has multiple packages).

**Comment by sfackler** [comment]
The default target string does not include a line number. You can make a logger implementation that renders that string if you'd like.

**Comment by keepsimple1** [comment]
Thanks!
