### ISSUE TITLE
Provide crate_name

### ISSUE THREAD

**Issue by juzi5201314** [rust-lang/log#456]
Just like file!, module_path!.

Benefits: 

Users can more clearly know which library the message is coming from.  

Developers can do special processing for certain crates logs (for example, filter out messages from certain libraries without changing the level).

Example: 

In a web project, the log can clearly show which messages come from the database (sqlx), which come from the http server (rocket), which come from any other library...
I believe that for a program that uses multiple crates, the log will become much clearer

**Comment by sfackler** [comment]
That is the first component of the module path.
