### ISSUE TITLE
Option to shorten `target` in `Record`

### ISSUE THREAD

**Issue by tekjar** [rust-lang/log#466]
https://docs.rs/log/0.4.14/log/struct.Record.html#method.target

In some cases where there are too many nested modules, `target` string becomes too long

```rust
mod a {
    mod b {
        mod c {}
    }
}
```

`target` in this case is `a::b::c`. Is there a way to just store target as `c`? While it's possible for log implementation to cut the string, it's going to be costly

If there is now way to do this now, would you be willing to accept a (feature flag) PR to make this possible?

**Comment by Thomasdezeeuw** [comment]
You can build a log record yourself and use [`RecordBuilder::target`](https://docs.rs/log/0.4.14/log/struct.RecordBuilder.html#method.target). The macros use the builtin `module_path!` and can't be changed at the moment.

**Comment by KodrAus** [comment]
If you don't want to split the target in your `Log` implementation then I think at this stage @Thomasdezeeuw's suggestion of tweaking how you capture records in your codebase is probably the best approach.

Shortening the path would unfortunately make filtering much less useful so I don't think we would want to do that within `log` itself.

Thanks for the suggestion @tekjar!
