### ISSUE TITLE
log prints nothing in lib.rs

### ISSUE THREAD

**Issue by wishyoushine** [rust-lang/log#474]
My lib.rs contains:
    ...
    extern crate log;
    use log::{warn};

    pub fn run(config: Config) -> Result<(), Box<dyn Error>> {
      warn!("run....");
      // other stuff
    ...

And when cargo run, the program runs fine but there is nothing print via warn!, any suggestions?

**Comment by Thomasdezeeuw** [comment]
The log crate is just a facade, you need an implementation to actually log messages. See https://github.com/rust-lang/log#in-executables.

**Comment by wishyoushine** [comment]
Yes, implementation like env_logger works in executables, but (env_logger)[https://github.com/env-logger-rs/env_logger/] says that: "env_logger makes sense when used in executables (binary projects). Libraries should use the log crate instead". And https://github.com/rust-lang/log says that: "Libraries should link only to the log crate, and use the provided macros to log whatever information will be useful to downstream consumers".
So this is just what the problem is: How to print logs to console or to a file via log in libraries?

**Comment by Thomasdezeeuw** [comment]
> Yes, implementation like env_logger works in executables, but env_logger(https://github.com/env-logger-rs/env_logger/) says that: "env_logger makes sense when used in executables (binary projects). Libraries should use the log crate instead". And https://github.com/rust-lang/log says that: "Libraries should link only to the log crate, and use the provided macros to log whatever information will be useful to downstream consumers". So this is just what the problem is: How to print logs to console or to a file via log in libraries?

Well libraries shouldn't run on their own so the user of the library should include an implementation, specifically where-ever the `main` function is defined should select the logging implementation. If you want to log in examples or in testing you can add a log implementation as dev-dependency, for example see: https://github.com/Thomasdezeeuw/heph/blob/aa6ccf79de85c0abccb6a26f920c7d9d405e80cf/Cargo.toml#L34-L37 and using it in an example: https://github.com/Thomasdezeeuw/heph/blob/aa6ccf79de85c0abccb6a26f920c7d9d405e80cf/examples/2_my_ip.rs#L19.

**Comment by wishyoushine** [comment]
Thanks, I got it! I need to add a log implementation like env_logger in executables, and then lib.rs with log macro like log::warn! can print log to console when do $ RUST_LOG="TRACE" cargon run. If no log implementation in the executables, then log macros in lib.rs like warn! or error! just do nothing as there is no log implementation in runtime(running process), thus cargo run just print no logs to console.
