### ISSUE TITLE
Build break in v0.4.16

### ISSUE THREAD

**Issue by znation** [rust-lang/log#497]
My project just picked up 0.4.16 as a downstream dependency, and it seems to have a build break when bringing in this version of `log`:

```
error[E0061]: this function takes 4 arguments but 3 arguments were supplied
    --> /Users/zach/.cargo/registry/src/github.com-1ecc6299db9ec823/slog-stdlog-4.1.0/lib.rs:244:9
     |
244  |         log::__private_api_log(format_args!("{}", lazy), level, &(target, info.module(), info.file(), info.line()));
     |         ^^^^^^^^^^^^^^^^^^^^^^ ------------------------  -----  -------------------------------------------------- supplied 3 arguments
     |         |
     |         expected 4 arguments
     |
note: function defined here
    --> /Users/zach/.cargo/registry/src/github.com-1ecc6299db9ec823/log-0.4.16/src/lib.rs:1603:8
     |
1603 | pub fn __private_api_log(
     |        ^^^^^^^^^^^^^^^^^
```

**Comment by znation** [comment]
Looking further into the error, I'm now suspicious that `slog-stdlog` is broken because it's relying on a private API in `log`, which changed out from underneath (reasonably so). Can anyone here confirm? If so then I think this issue can be closed and moved to the `slog-stdlog` crate.

**Comment by sfackler** [comment]
Yes, this is slog-stdlog's problem: #493

**Comment by znation** [comment]
Thanks @sfackler, this is a dupe of #493.
