### ISSUE TITLE
Feature Request: More levels specific to library usage

### ISSUE THREAD

**Issue by mimullin-bbry** [rust-lang/log#498]
Hello

This is a bit of a "pie in the sky" request.  But you miss 100% of the shots you don't take.

I would like to see two additional "lowest level" logging levels added to log.

debug_library! and trace_library!

I would like these levels because in the rust ecosystem libraries tend to use debug! and trace!, and they spew a lot of print statements.  This effectively renders my usage of these two levels useless as my logging gets lost in the noise.

If two new log levels, specifically to be used by library creators is created, My application can use all 5 log levels rather than be limited to error! warn! and info!

Thank you for reading.

**Comment by sfackler** [comment]
I would recommend using a logging implementation that allows you to filter verbosity based on the module.

**Comment by Thomasdezeeuw** [comment]
I agree with @sfackler furthermore it would be quite a lot of churn before all libraries would use any new logging levels. Filtering based on [target](https://docs.rs/log/latest/log/struct.Record.html#method.target) or [module](https://docs.rs/log/latest/log/struct.Record.html#method.module_path) would be the quicker (and likely better) solution.

**Comment by KodrAus** [comment]
I think it's safe to say this isn't a direction we'd want to head in, but thanks for the suggestion @mimullin-bbry! It's an important use-case, but we think it's best handled by filtering on other metadata in the log than just the level.
