### ISSUE TITLE
log crate does not support logging

### ISSUE THREAD

**Issue by mabushey** [rust-lang/log#501]
It's quite confusing that this is a crate for printing, NOT logging. Could logging to a log file be added, or is there a better crate for logging?

**Comment by sfackler** [comment]
I don't understand your question. Can you clarify a) what printing this crate is doing, and b) how logging differs from printing?

**Comment by Thomasdezeeuw** [comment]
@mabushey do mean the log crate doesn't do anything by default? This is on purpose as it only provides a standardised interface. If your looking for an implementation see https://github.com/rust-lang/log#in-executables.

**Comment by KodrAus** [comment]
As @Thomasdezeeuw suggested it sounds like the _In Executables_ section of the README is what you're looking for that calls out various logging backends for the console, files, databases etc.
