### ISSUE TITLE
Is it necessary to use Ordering::SeqCst in the log!  ??

### ISSUE THREAD

**Issue by relufi** [rust-lang/log#509]
```rust
pub fn logger() -> &'static dyn Log {
   // Is it necessary to use Ordering::SeqCst in log!
    if STATE.load(Ordering::SeqCst) != INITIALIZED {
        static NOP: NopLogger = NopLogger;
        &NOP
    } else {
        unsafe { LOGGER }
    }
}
```

See the implementation of std::lazy::SyncOnceCell or parking_lot::Once

**Comment by relufi** [comment]
I tried to use a more relaxed order and wrote a [test](https://github.com/relufi/log/blob/8b5da221f8c53211a5534fe530adb53abc31b430/src/lib.rs#L1969)
https://github.com/relufi/log/blob/use-relaxed-memory-barriers/src/lib.rs

However, when I tried to change all the memory order to Relaxed and tested on the arm platform, there was no visibility problem either.

**Comment by KodrAus** [comment]
I think the ordering there could probably be downgraded so long as we always see the store of `STATE` after the store of `LOGGER`. The orderings on initialization are also pretty conservative, but it's always hard to tell whether that's because they're necessary or because they haven't been optimized.

**Comment by relufi** [comment]
Reference std::sync::Once SeqCst is not necessary, I am concerned that using SeqCst in every log! will affect performance (log! is too common and SeqCst is too expensive on some platforms).
If you're worried about problems you can just introduce std::sync::Once or parking_lot::Once to avoid them.

**Comment by relufi** [comment]
I am using a translation tool, so please bear with me if I make any mistakes.

**Comment by Thomasdezeeuw** [comment]
Since #610 we're using `Acquire` in `logger`, so closing this.
