### ISSUE TITLE
inconsistent results when using the log crate in an embedded setup

### ISSUE THREAD

**Issue by nihalpasham** [rust-lang/log#510]
*I guess this is not exactly an issue, but I couldn't find a discussions tab, so I thought I'll start here. If this is not the right place for this, please point me in right direction.*

I'm using the log crate as my logging facade, to log a bare-metal app built for the `rpi4`. The entire app is single threaded (with interrupts disabled) i.e. we're running on a single core with just one main thread to ensure there aren't any races.

My current [logging implementation](https://github.com/nihalpasham/rustBoot/blob/main/boards/hal/src/rpi/rpi4/log/print.rs) uses a simple [UART-based](https://github.com/nihalpasham/rustBoot/blob/main/boards/hal/src/rpi/rpi4/bsp/drivers/uart0.rs) logger, which works, but when I add the logging facade, I get some inconsistent results. [More info here](https://github.com/rust-embedded/rust-raspberrypi-OS-tutorials/discussions/160)

So, I was wondering if I'm doing something wrong here or if anyone knows of a working impl that uses the log crate in a bare-metal setup.

**Comment by KodrAus** [comment]
Hi @nihalpasham :wave: Hmm, this is a domain I'm not really familiar with, but the `log` crate doesn't do anything particularly fancy or bespoke with its global logger. It just sets a `static`. If you do get to the bottom of this and find it's something we're doing wrong here we can fix it up, but unfortunately I don't think there's much else we could offer.

I'll leave this open for now though in case anybody else more familiar with that space can chime in.

Good luck!

**Comment by KodrAus** [comment]
Just coming back through some triage. It's been a little while here so I'll go ahead and close this one, I hope you managed to find a solution @nihalpasham!
