### ISSUE TITLE
logging without file/line?

### ISSUE THREAD

**Issue by stevefan1999-personal** [rust-lang/log#512]
Out of privacy concern I don't want to include references to the file and lines so as to make reverse engineer harder, but far as I see there is no way to opt out to have logging without those information in the standard macros. I can always add the record myself but it would be tedious.

**Comment by sfackler** [comment]
You can configure your logging implementation to not output them if you'd like.

**Comment by Thomasdezeeuw** [comment]
@stevefan1999-personal if you can't control the logging implementation you can also build your own log records using [`RecordBuilder`](https://docs.rs/log/latest/log/struct.RecordBuilder.html), easiest is likely to copy the `log!` macro code, this way at least your code won't expose the file/line.

**Comment by KodrAus** [comment]
Coming back through some triage. This issue hasn’t seen any activity in a while so I’ll go ahead and close it.

For cases where the `log` macros don’t serve a particular use-case we do provide lower-level APIs you can build off like @Thomasdezeeuw pointed out that may better cater to your needs.
