### ISSUE TITLE
Deprecated warning in windows workflow

### ISSUE THREAD

**Issue by hellow554** [rust-lang/log#518]
https://github.com/rust-lang/log/runs/6683448799?check_suite_focus=true#step:3:6

```
error: DEPRECATED: future versions of rustup will require --force-non-host to install a non-host toolchain as the default.
warning: toolchain 'stable-x86_64' may not be able to run on this system.
warning: If you meant to build software to target that platform, perhaps try `rustup target add x86_64` instead?
```

I don't know how to handle this, but it should be addressed soon

**Comment by KodrAus** [comment]
Hmm, maybe we've got a typo in our build script. I'll take a look, thanks for pointing this out @hellow554 :eyes:
