### ISSUE TITLE
Why Is There No `log::flush()`?

### ISSUE THREAD

**Issue by AldaronLau** [rust-lang/log#523]
A library that depends on the log crate can't flush buffered messages without depending on a logging implementation.  It doesn't make much sense to me that the `flush()` method is required for `Log` implementations, unused by the log crate, and also inaccessible to potential callers (unless the type implementing `Log` is exposed by the crate with the logger implementation, in which case it's only available for application consumers and not libraries).

**Comment by sfackler** [comment]
`log::logger().flush()`.

**Comment by AldaronLau** [comment]
Thanks, I missed that when looking through the docs!
