### ISSUE TITLE
`AtomicUsize` has an unsound `Sync` impl

### ISSUE THREAD

**Issue by djkoloski** [rust-lang/log#534]
The comment on the `Sync` impl for `AtomicUsize` is:

```rust
// Any platform without atomics is unlikely to have multiple cores, so
// writing via Cell will not be a race condition.
```

While this may be true in practice, it's still technically incorrect and could open the door for bad codegen. Is there some background on why this impl is required even for platforms that don't support atomics?

**Comment by Thomasdezeeuw** [comment]
I believe this was added to support embedded system which don't support atomics (or threads). I don't even think it's possible to support threads without some of atomics, but I could be wrong here.

**Comment by Thomasdezeeuw** [comment]
This is documented in [`set_logger_racy`](https://docs.rs/log/latest/log/fn.set_logger_racy.html).

**Comment by notgull** [comment]
I see, I missed that. In that case it should be sound since it is only used when safety can be enforced.

**Comment by djkoloski** [comment]
Since `MAX_LOG_LEVEL_FILTER` is also an `AtomicUsize`, doesn't that mean that `set_max_level` should be set up the same way? i.e. `set_max_level` should be behind a `#[cfg(atomic_cas)]` and an unsafe `set_max_level_racy` should be available everywhere.
