### ISSUE TITLE
Please `impl` Log for `Vec<T>` where `T: Log`, so that multiple parallel loggers can be set

### ISSUE THREAD

**Issue by Boscop** [rust-lang/log#537]
Please `impl` Log for `Vec<T>` where `T: Log`, so that multiple parallel loggers can be set.

In my use case, I need to log in parallel to multiple loggers that are imported from different crates.

**Comment by KodrAus** [comment]
Hi @Boscop :wave:

This seems like something you could reasonably implement yourself in a wrapper type. In general, I think we should avoid generic implementations in this library that layer any semantics over just a smart pointer.

**Comment by ckane** [comment]
You might want to look at https://docs.rs/simplelog/latest/simplelog/struct.CombinedLogger.html

**Comment by Thomasdezeeuw** [comment]
Seems to solved in an external crate, so closing.
