### ISSUE TITLE
error: failed to run custom build command for `log v0.4.17`

### ISSUE THREAD

**Issue by petrisch** [rust-lang/log#549]
`error: failed to run custom build command for log v0.4.17`

`Caused by:
  could not execute process C:\Users\patrick.joerg\repo\typst\target\release\build\log-e3dcc535df98cdc4\build-scrip
t-build (never executed)`

This is on windows with rust 1.68.2 (probably have been the same with .1) with stable-x86_64-pc-windows-msvc
I have no idea if this is even the right place for it. Let me know what information I can provide.

Greetz and otherwise just ignore 😄

**Comment by petrisch** [comment]
Building with +nightly works, so this is probably a known fact I am not aware of.

**Comment by Thomasdezeeuw** [comment]
@petrisch can you try running `cargo clean` and building again? Sometimes the build command fails to no clear reason and a wipe of the cache seems to solve it, for example see https://github.com/rust-lang/log/issues/503 and https://github.com/rust-lang/log/issues/542.

**Comment by petrisch** [comment]
@Thomasdezeeuw jeah I tried this, but it didn't help this time.

Not shure thoug because I use cargo alot for directly installing some tools, that all need `log`.
`deno`, `mdbook`, `mdcat` just to name a few. And I install them directly from crates.io with `cargo install-update`

But even with building for example `typst-cli` from source after a `cargo clean` i get this error.
Does `cargo install-update` generate another cache that interferes here and can I clean that one as well?

**Comment by Thomasdezeeuw** [comment]
> Not shure thoug because I use cargo alot for directly installing some tools, that all need `log`. `deno`, `mdbook`, `mdcat` just to name a few. And I install them directly from crates.io with `cargo install-update`
> 
> But even with building for example `typst-cli` from source after a `cargo clean` i get this error. Does `cargo install-update` generate another cache that interferes here and can I clean that one as well?

Cargo uses a cache/build per workspace (directory with a `Cargo.toml` file), so it shouldn't interfere.

Odd that it does work on nightly as don't know if any changes that would affect the running of the build script.

Could it be that maybe some anti-virus/malware software is preventing the running of the script?

**Comment by petrisch** [comment]
Ah yes you are right. It was the antivirus.
Thanks for pointing me in that direction.
Reported it...
