### ISSUE TITLE
What to do about the integration list in the README

### ISSUE THREAD

**Issue by KodrAus** [rust-lang/log#551]
In https://github.com/rust-lang/log/pull/548#issuecomment-1486869928 @JohnTitor brought up the broader question of what to do with the list of integrations listed in the README. They're currently presented as "the most popular" implementations out there. Right now the list isn't really curated that way; if there's a new crate that integrates with `log` then we add it to the list.

The function the list serves is giving users a kick-start to get actual data out of `log`, which on its own simply pipes your events into oblivion.

Alternative strategies to achieving that function are:

- Linking a Cargo keyword for `log` or `logger` as mentioned in the linked comment.
- Updating the wording of the README to not suggest the list is curated in any way besides listing libraries that integrate with `log`. It's up to end-users to evaluate the suitability of these libraries for their own needs.

**Comment by NobodyXu** [comment]
Would it be a good idea to mention `tracing_log` in the list, for it enables forwarding `tracing` to `log` or visa versa?

**Comment by Thomasdezeeuw** [comment]
Maybe we should just change the wording? For example from:

> There are many available implementations to choose from, here are some of the most popular ones:

To:

> There are many available implementations to choose from, here are some options:

**Comment by KodrAus** [comment]
@Thomasdezeeuw that sounds good to me.

**Comment by Thomasdezeeuw** [comment]
@KodrAus any further changes we want to make?

**Comment by KodrAus** [comment]
@Thomasdezeeuw I think it's all ok now. Are you happy for this issue to be closed?
