### ISSUE TITLE
How do I set log level in Windows?

### ISSUE THREAD

**Issue by Agent-E11** [rust-lang/log#598]
I am trying to use log on windows, and I have tried:

```ps1
set RUST_LOG=dubug
cargo run
```
```ps1
$RUST_LOG=debug
cargo run
```
```ps1
$RUST_LOG=debug && cargo run
```
```ps1
$RUST_LOG=debug; cargo run
```

And the only logs I am getting are `error`s

**Comment by Thomasdezeeuw** [comment]
You need to set an environment variable, see https://stackoverflow.com/questions/55500857/how-can-i-set-the-environment-variables-in-windows.

**Comment by Agent-E11** [comment]
@Thomasdezeeuw I believe I have already tried that. `set RUST_LOG=debug` didn't work.

**Comment by Agent-E11** [comment]
I found out from another source:
```ps1
$Env:<variable-name> = "<value>"
```
```ps1
$Env:RUST_LOG = "debug"
```
