### ISSUE TITLE
Add tests that check the line numbers

### ISSUE THREAD

**Issue by Thomasdezeeuw** [rust-lang/log#601]
We currently don't have any.

**Comment by DIvkov575** [comment]
Im pretty new to contributing, but I would love to contribute to this repo. Would this be a good issue to start with?

**Comment by Thomasdezeeuw** [comment]
> Im pretty new to contributing, but I would love to contribute to this repo. Would this be a good issue to start with?

Hey @DIvkov575 sorry for the delayed response, I've been traveling.

I think it will be a good first issue. I think the easiest way to get started is to look at `tests/filters.rs`for inspiration. If you have a any questions or you get stuck somewhere feel free to ask!
