### ISSUE TITLE
Setting the file/line shown in a log message

### ISSUE THREAD

**Issue by bconn98** [rust-lang/log#609]
Hello,

I am trailing running a [rust based logger from C++](https://github.com/bconn98/logger). However, I noticed that the line file and number get generated from the rust code. That makes sense to me, however, I'm wondering if it's possible to override those values? It looks like the `Record` that holds this value is generated and owned by the `log` macro and doesn't have direct access by the user.

**Comment by Thomasdezeeuw** [comment]
I'm afraid you can't overwrite the file and line number using the macros, however you can build your own log record using [`log::RecordBuilder`](https://docs.rs/log/latest/log/struct.RecordBuilder.html), you can view [`log_impl`](https://github.com/rust-lang/log/blob/c5ddd6fbe1403b8b01c362cd676c9cc0e74b2016/src/__private_api.rs#L55-L66) (the actual implementation) as an example.

**Comment by bconn98** [comment]
Okay, yeah I was envisioning something similar to that with manually building the record and passing it along. Thanks Tom. I'll mess around with it.

**Comment by bconn98** [comment]
Any suggestions for generating `fmt::Argument`s outside of the log macro?

**Comment by Thomasdezeeuw** [comment]
Can only be done using [`format_args!`](https://doc.rust-lang.org/std/macro.format_args.html).

**Comment by bconn98** [comment]
Yup, messed around with that extensively but hitting a wall on the temporary nature of the returned Arguments

**Comment by Thomasdezeeuw** [comment]
Yeah, best (or only) usage is passing it directly to `Recordbuilder::args`.

**Comment by bconn98** [comment]
Yup while doing that I saw the temporary issue. FWIW, the note doesn't resolve the issue.
```
error[E0716]: temporary value dropped while borrowed
  --> src/lib.rs:49:15
   |
49 |         .args(format_args!("{}", msg))
   |               ^^^^^^^^^^^^^^^^^^^^^^^ creates a temporary value which is freed while still in use
...
54 |         .line(Some(line));
   |                          - temporary value is freed at the end of this statement
55 |
56 |     logger().log(&builder.build());
   |                   ------- borrow later used here
   |
   = note: this error originates in the macro `format_args` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider using a `let` binding to create a longer lived value
   |
48 ~     let binding = format_args!("{}", msg);
49 ~     builder
50 ~         .args(binding)
   |
```

**Comment by NobodyXu** [comment]
You might want to move the builder to be inside `logger.log()`, `format_args!` contains temporary in the macro after expanded so it cannot be binded to a variable, only use as a temporary.
