### ISSUE TITLE
Log timestamp not match my timezone.

### ISSUE THREAD

**Issue by getcisher** [rust-lang/log#631]
How to change timestamp when logging to match my timezone?
I don't see any document for setup timezone or at least reference timezone in my machine.
My timezone is Bangkok/TH +7hr

**Comment by Thomasdezeeuw** [comment]
This crate is only a facade for logging. I doesn't do the actual logging and it does not add a timestamp to the logs. Please take a look at `Cargo.toml` to find the actual implementation.
