### ISSUE TITLE
when i use cargo build command to build log ， i don't know what wrong  and how to solve it?

### ISSUE THREAD

**Issue by KairusZhang** [rust-lang/log#640]
error[E0658]: `cfg(target_has_atomic)` is experimental and subject to change
   --> src/lib.rs:396:11
    |
396 | #[cfg(not(target_has_atomic = "ptr"))]
    |           ^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #32976 <https://github.com/rust-lang/rust/issues/32976> for more information
    = help: add `#![feature(cfg_target_has_atomic)]` to the crate attributes to enable

**Comment by KairusZhang** [comment]
i try to change the rustc version to 
rustup default nightly-2024-05-01-x86_64-unknown-linux-gnu 
And show the version of rustc 1.84.0-nightly (9322d183f 2024-10-14)
, but all of them are useless!!

**Comment by Thomasdezeeuw** [comment]
Can you update to a Rust version newer than 1.60? This is the minimum supported version: https://github.com/rust-lang/log?tab=readme-ov-file#minimum-supported-rustc.

**Comment by KairusZhang** [comment]
yes, i solved it by uninstall all other version
$ rustup toolchain list  && rustup uninstall XXXX-linux-gnu*;
$ rustc --version
only keep the latest rustc 1.84.0-nightly (9322d183f 2024-10-14);

i find the problem was caused by Cargo.toml dependencies  , there are some other crate which is too old and them have dependencies on oler log crate. 

so i must keep the dependencies and version of rustc in latest sates.\\thanks for your suggestion,.
