### ISSUE TITLE
May Return Absolute File Paths in Logs Under Certain Conditions？

### ISSUE THREAD

**Issue by Dynasty-CS** [rust-lang/log#649]
https://github.com/rust-lang/log/commit/c9e5e13e9b02ec80e784c6fe4deacdc8f3194fca
While using the #[track_caller] attribute with the following function:

#[track_caller]
pub fn loc() -> &'static Location<'static> {
    Location::caller()
}

it seems that in some cases, the log outputs might include absolute file paths instead of relative paths.

**Comment by Thomasdezeeuw** [comment]
This is controlled by rustc, not the log crate, I don't think we can do much here.

I think rustc has some options here, e.g. `--remap-path-prefix` or https://github.com/rust-lang/rust/issues/111540.

**Comment by Dynasty-CS** [comment]
Oh thank you a lot
