### ISSUE TITLE
Are these `#[inline]` helping?

### ISSUE THREAD

**Issue by dpc** [rust-lang/log#92]
I've noticed that `log` crate goes out of it's way to add `#[inline]` in a lot of places. I'd like to ask - is it worth it with a current rust compiler? Any experiences and measurements? 

Corresponding slog-rs issue: https://github.com/dpc/slog-rs/issues/25

**Comment by dtolnay** [comment]
Here is the latest wisdom about `#[inline]`: https://github.com/rust-lang/rust/pull/52704#issuecomment-408536474.
